name: Build and Publish Airportlog
on: [push]

jobs:
    build-and-deploy:
        name: Build and deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Build the angular site
              run: |
                  docker run \
                  -v ${{ github.workspace }}:/app -v ${{ github.workspace }}/build:/app/build \
                  trion/ng-cli-karma:latest /bin/bash -c "chmod 777 /app && npm ci && ng build --prod --base-href airportlog"
            - name: List output files 1
              run: ls -la
            - name: List output files 2
              run: ls -la dist
            - name: Deploy to GitHub Pages
              uses: Cecilapp/GitHub-Pages-deploy@master
              env:
                  EMAIL: markus.eckstein@gmx.de
                  GH_TOKEN: ${{ secrets.ACCESS_TOKEN }} # https://github.com/settings/tokens
                  BUILD_DIR: dist/ # "_site/" by default
